export const productsData = [
  {
    id: Math.random().toString(),
    model: 'Negresco Supreme',
    fakePrice: 135,
    realPrice: 95,
    images: '2.jpg',
    description: 'Negresco Supreme',
  },
  {
    id: Math.random().toString(),
    model: 'Negresco Supreme',
    fakePrice: 135,
    realPrice: 95,
    images: '2.jpg',
    description: 'Negresco Supreme',
  },
  {
    id: Math.random().toString(),
    model: 'Negresco Supreme',
    fakePrice: 135,
    realPrice: 95,
    images: '2.jpg',
    description: 'Negresco Supreme',
  },
  {
    id: Math.random().toString(),
    model: 'Negresco Supreme',
    fakePrice: 135,
    realPrice: 95,
    images: '2.jpg',
    description: 'Negresco Supreme',
  },
  {
    id: Math.random().toString(),
    model: 'Negresco Supreme',
    fakePrice: 135,
    realPrice: 95,
    images: '2.jpg',
    description: 'Negresco Supreme',
  },
  {
    id: Math.random().toString(),
    model: 'Negresco Supreme',
    fakePrice: 135,
    realPrice: 95,
    images: '2.jpg',
    description: 'Negresco Supreme',
  },
  {
    id: Math.random().toString(),
    model: 'Negresco Supreme',
    fakePrice: 135,
    realPrice: 95,
    images: '2.jpg',
    description: 'Negresco Supreme',
  },
  {
    id: Math.random().toString(),
    model: 'Negresco Supreme',
    fakePrice: 135,
    realPrice: 95,
    images: '2.jpg',
    description: 'Negresco Supreme',
  },
  {
    id: Math.random().toString(),
    model: 'Negresco Supreme',
    fakePrice: 135,
    realPrice: 95,
    images: '2.jpg',
    description: 'Negresco Supreme',
  },
  {
    id: Math.random().toString(),
    model: 'Negresco Supreme',
    fakePrice: 135,
    realPrice: 95,
    images: '2.jpg',
    description: 'Negresco Supreme',
  },
  {
    id: Math.random().toString(),
    model: 'Negresco Supreme',
    fakePrice: 135,
    realPrice: 95,
    images: '2.jpg',
    description: 'Negresco Supreme',
  },
  {
    id: Math.random().toString(),
    model: 'Negresco Supreme',
    fakePrice: 135,
    realPrice: 95,
    images: '2.jpg',
    description: 'Negresco Supreme',
  },
  {
    id: Math.random().toString(),
    model: 'Negresco Supreme',
    fakePrice: 135,
    realPrice: 95,
    images: '2.jpg',
    description: 'Negresco Supreme',
  },
  {
    id: Math.random().toString(),
    model: 'Negresco Supreme',
    fakePrice: 135,
    realPrice: 95,
    images: '2.jpg',
    description: 'Negresco Supreme',
  },
  {
    id: Math.random().toString(),
    model: 'Negresco Supreme',
    fakePrice: 135,
    realPrice: 95,
    images: '2.jpg',
    description: 'Negresco Supreme',
  },
];
